-- Schema required for the members-only allowlist + (optional) members resources.
-- Run this in Supabase Dashboard → SQL Editor.

-- 1) Allowlist table used to decide whether a signed-in user is "registered".
create table if not exists public.allowed_members (
  email text primary key,
  name text,
  source text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

alter table public.allowed_members enable row level security;

revoke all on table public.allowed_members from anon;
grant select on table public.allowed_members to authenticated;

drop policy if exists allowed_members_select_own_email on public.allowed_members;
create policy allowed_members_select_own_email
  on public.allowed_members
  for select
  to authenticated
  using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- Helpful for case-insensitive lookups if you ever switch to ilike queries.
-- (The Edge Functions normalize emails to lowercase already.)
create index if not exists allowed_members_created_at
  on public.allowed_members (created_at);

-- 2) Optional: store members-only winners content in the database (instead of committing it to git).
-- The `winners` Edge Function can read this table using the service role key after verifying membership.
create table if not exists public.winners_payload (
  year int primary key,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.winners_payload enable row level security;

grant select on table public.winners_payload to anon, authenticated;

-- year 9999 is a sentinel row holding the public AI/AECO Resources payload,
-- not a winners year. Every real winners year stays members-only.
drop policy if exists winners_payload_public_resources_2026 on public.winners_payload;
drop policy if exists winners_payload_public_resources on public.winners_payload;
create policy winners_payload_public_resources
  on public.winners_payload
  for select
  to anon, authenticated
  using (year = 9999);

create index if not exists winners_payload_updated_at
  on public.winners_payload (updated_at);

-- 3) Slide download events for members-only analytics.
create table if not exists public.slide_download_events (
  id bigint generated by default as identity primary key,
  email text not null,
  slide_id text not null,
  slide_url text not null,
  event_at timestamptz not null default now(),
  user_agent text,
  referrer text,
  request_method text,
  metadata jsonb
);

alter table public.slide_download_events enable row level security;

revoke all on table public.slide_download_events from anon, authenticated;

create index if not exists slide_download_events_event_at
  on public.slide_download_events (event_at desc);

create index if not exists slide_download_events_email_event_at
  on public.slide_download_events (email, event_at desc);

create index if not exists slide_download_events_slide_id_event_at
  on public.slide_download_events (slide_id, event_at desc);

-- 4) Admin allowlist for private analytics endpoints.
create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default now(),
  created_by text
);

alter table public.admin_users enable row level security;

revoke all on table public.admin_users from anon, authenticated;

create index if not exists admin_users_created_at
  on public.admin_users (created_at desc);

-- 5) Page visit events for website analytics.
create table if not exists public.page_visit_events (
  id bigint generated by default as identity primary key,
  email text,
  path text not null,
  page_title text,
  referrer text,
  session_id text,
  event_at timestamptz not null default now(),
  user_agent text,
  metadata jsonb
);

alter table public.page_visit_events enable row level security;

revoke all on table public.page_visit_events from anon, authenticated;

create index if not exists page_visit_events_event_at
  on public.page_visit_events (event_at desc);

create index if not exists page_visit_events_path_event_at
  on public.page_visit_events (path, event_at desc);

create index if not exists page_visit_events_email_event_at
  on public.page_visit_events (email, event_at desc);

create index if not exists page_visit_events_session_id_event_at
  on public.page_visit_events (session_id, event_at desc);
