-- Schema required for the members-only allowlist + (optional) members resources.
-- Run this in Supabase Dashboard → SQL Editor.

-- 1) Allowlist table used to decide whether a signed-in user is "registered".
create table if not exists public.allowed_members (
  email text primary key,
  name text,
  source text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

-- Helpful for case-insensitive lookups if you ever switch to ilike queries.
-- (The Edge Functions normalize emails to lowercase already.)
create index if not exists allowed_members_created_at
  on public.allowed_members (created_at);

-- 2) Optional: dynamic members resources table.
create table if not exists public.members_resources (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  note text,
  sort_order int,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists members_resources_active_sort
  on public.members_resources (active, sort_order, created_at);
