-- Create members_resources table for dynamic members-only content
create table if not exists public.members_resources (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  note text,
  sort_order int,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists members_resources_active_sort
  on public.members_resources (active, sort_order, created_at);

-- Disable RLS to allow Edge Functions to access
ALTER TABLE public.members_resources DISABLE ROW LEVEL SECURITY;
