-- Track members' slide download/view redirects for analytics.

create table if not exists public.slide_download_events (
  id bigint generated by default as identity primary key,
  email text not null,
  slide_id text not null,
  slide_url text not null,
  event_at timestamptz not null default now(),
  user_agent text,
  referrer text,
  request_method text,
  metadata jsonb
);

alter table public.slide_download_events enable row level security;

revoke all on table public.slide_download_events from anon, authenticated;

create index if not exists slide_download_events_event_at
  on public.slide_download_events (event_at desc);

create index if not exists slide_download_events_email_event_at
  on public.slide_download_events (email, event_at desc);

create index if not exists slide_download_events_slide_id_event_at
  on public.slide_download_events (slide_id, event_at desc);
