-- Website page visit analytics events.

create table if not exists public.page_visit_events (
  id bigint generated by default as identity primary key,
  email text,
  path text not null,
  page_title text,
  referrer text,
  session_id text,
  event_at timestamptz not null default now(),
  user_agent text,
  metadata jsonb
);

alter table public.page_visit_events enable row level security;

revoke all on table public.page_visit_events from anon, authenticated;

create index if not exists page_visit_events_event_at
  on public.page_visit_events (event_at desc);

create index if not exists page_visit_events_path_event_at
  on public.page_visit_events (path, event_at desc);

create index if not exists page_visit_events_email_event_at
  on public.page_visit_events (email, event_at desc);

create index if not exists page_visit_events_session_id_event_at
  on public.page_visit_events (session_id, event_at desc);
